[build]
# Use incremental compilation for faster builds
incremental = true

[target.x86_64-unknown-linux-gnu]
# Linux-specific linker configuration
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
# Development profile - fast compilation
opt-level = 0
debug = true
split-debuginfo = "unpacked"

[profile.release]
# Release profile - optimized builds
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
