name: 'Setup Ubuntu Dependencies'
description: 'Install system dependencies for Tauri on Ubuntu'

inputs:
  e2e:
    description: 'Install E2E testing dependencies (xvfb, libxdo-dev, etc.)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Tauri system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf

    - name: Install E2E test dependencies
      if: ${{ inputs.e2e == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y \
          xvfb \
          libxdo-dev \
          libglib2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libatk1.0-dev \
          libgdk-pixbuf2.0-dev \
          libsoup-3.0-dev \
          libjavascriptcoregtk-4.1-dev
