name: 'Setup Ubuntu Dependencies'
description: 'Install system dependencies for Tauri on Ubuntu'

runs:
  using: 'composite'
  steps:
    - name: Install Tauri system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf
