name: 'Setup Ubuntu Dependencies'
description: 'Install system dependencies for Tauri 2 on Ubuntu'

runs:
  using: 'composite'
  steps:
    - name: Install Tauri 2 system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libwebkit2gtk-4.1-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libxdo-dev \
          file \
          patchelf
